<script setup>
import AuthLayout from '@/Layouts/AuthLayout.vue'
import { Head } from '@inertiajs/vue3'
import { useGuestAssets } from '@/composables/Guest'

const { asset } = useGuestAssets()
</script>

<template>
    <AuthLayout authImage="terms.svg">
        <Head title="Privacy Policy" />

        <div class="legal-page">
            <h1 class="auth-title">Privacy Policy</h1>
            
            <div class="legal-section">
                <p class="legal-text">
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p class="legal-text">
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>
            </div>

            <div class="legal-section">
                <h2>Interpretation and Definitions</h2>
                <h3>Interpretation</h3>
                <p class="legal-text">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                
                <h3>Definitions</h3>
                <ul class="legal-list-bullet">
                    <li><strong>Account</strong> means a unique account created for You to access our Service.</li>
                    <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to STS Inc, 3518 Yellow Jacket Lane, Southport, FL, 32409.</li>
                    <li><strong>Cookies</strong> are small files placed on Your device containing the details of Your browsing history.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service.</li>
                </ul>
            </div>

            <div class="legal-section">
                <h2>Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p class="legal-text">While using Our Service, We may ask You to provide Us with certain personally identifiable information, including but not limited to:</p>
                <ul class="legal-list-bullet">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                </ul>
            </div>

            <div class="legal-section">
                <h2>Use of Your Personal Data</h2>
                <p class="legal-text">The Company may use Personal Data for the following purposes:</p>
                <ul class="legal-list-bullet">
                    <li><strong>To provide and maintain our Service</strong></li>
                    <li><strong>To manage Your Account</strong></li>
                    <li><strong>For the performance of a contract</strong></li>
                    <li><strong>To contact You</strong> via email, telephone, or SMS</li>
                    <li><strong>To manage Your requests</strong></li>
                </ul>
            </div>

            <div class="legal-section">
                <h2>Contact Us</h2>
                <p class="legal-text">If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul class="legal-list-bullet">
                    <li>By email: <a href="mailto:support@ship-sts.com">support@ship-sts.com</a></li>
                </ul>
            </div>
        </div>
    </AuthLayout>
</template>

<style scoped>
:deep(.content-body) {
    max-width: 800px;
}

.legal-page {
    color: #475569;
    line-height: 1.8;
    padding-bottom: 60px;
}

.legal-section {
    margin-bottom: 48px;
}

.legal-section h2 {
    font-size: 20px;
    color: #1e293b;
    margin-bottom: 24px;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 1px;
    border-left: 4px solid #0d9488;
    padding-left: 15px;
}

.legal-section h3 {
    font-size: 17px;
    color: #0d9488;
    margin-top: 24px;
    margin-bottom: 12px;
    font-weight: 700;
}

.legal-section h4 {
    font-size: 15px;
    color: #334155;
    margin-bottom: 10px;
    font-weight: 700;
}

.legal-text {
    font-size: 15px;
    margin-bottom: 16px;
}

.legal-list-bullet {
    padding-left: 25px;
    list-style-type: none;
}

.legal-list-bullet li {
    font-size: 15px;
    margin-bottom: 12px;
    position: relative;
    padding-left: 15px;
}

.legal-list-bullet li::before {
    content: "•";
    color: #0d9488;
    font-weight: bold;
    display: inline-block;
    width: 1em;
    margin-left: -1em;
}

.legal-list-bullet li strong {
    color: #1e293b;
}

a {
    color: #0d9488;
    font-weight: 700;
    text-decoration: none;
    border-bottom: 1px solid rgba(13, 148, 136, 0.3);
    transition: all 0.2s;
}

a:hover {
    color: #0f766e;
    border-bottom-color: #0f766e;
}
</style>
